### PR TITLE
Elbow fixes

### PR DESCRIPTION
**Pull request by TriPham2021**
Hi

Pls try it first. I cannot test it.

Thank you

### CODE REVIEW

**Comment by TriPham2021** [comment]
Hi

I tried it already. It was great.

Thank you

**Comment by Baonguyenle** [comment]
Dear Tri
I can't merge it because I can't run the code

**Comment by Baonguyenle** [comment]
Dear Tri
The code says the problem is joystick_d_position = controller.axisD.position()

**Comment by TriPham2021** [comment]
Hi

I just don't understand. I can't find any problem. The VS code can't too. Check everything again and, if there is something wrong
tell me

Thank you.

**Comment by Baonguyenle** [comment]
Dear Tri 
It works really good!
Bao

**Pull request merged**
